# docker-compose.yml (for local development)
version: '3.8'
services:
  library-management:
    build: .
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=development
      - SPRING_PROFILES_ACTIVE=development
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped