# kubernetes/configmap-prod.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: library-app-config
  namespace: default
data:
  APP_ENV: "prod"
  SPRING_PROFILES_ACTIVE: "prod"
  logging.level.com.library: "INFO"
  DB_HOST: "mysql-service"
  DB_NAME: "library_prod"
  DB_USER: "app_user"